"""Change quantity

Revision ID: 7f64245bdf2c
Revises: 96da04205528
Create Date: 2025-11-18 21:45:57.056734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f64245bdf2c'
down_revision: Union[str, Sequence[str], None] = '96da04205528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('quantity', sa.Integer(), nullable=False))
    op.drop_column('cart_items', 'quanity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('quanity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('cart_items', 'quantity')
    # ### end Alembic commands ###
