"""Create CartitemSecond

Revision ID: 96da04205528
Revises: 2fb8e59367b2
Create Date: 2025-11-18 14:37:01.505692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96da04205528'
down_revision: Union[str, Sequence[str], None] = '2fb8e59367b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('buyer_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_cart_items_user_id'), table_name='cart_items')
    op.drop_constraint(op.f('uq_cart_items_user_product'), 'cart_items', type_='unique')
    op.create_unique_constraint('uq_cart_items_user_product', 'cart_items', ['buyer_id', 'product_id'])
    op.create_index(op.f('ix_cart_items_buyer_id'), 'cart_items', ['buyer_id'], unique=False)
    op.drop_constraint(op.f('cart_items_user_id_fkey'), 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'users', ['buyer_id'], ['id'], ondelete='CASCADE')
    op.drop_column('cart_items', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key(op.f('cart_items_user_id_fkey'), 'cart_items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_cart_items_buyer_id'), table_name='cart_items')
    op.drop_constraint('uq_cart_items_user_product', 'cart_items', type_='unique')
    op.create_unique_constraint(op.f('uq_cart_items_user_product'), 'cart_items', ['user_id', 'product_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_cart_items_user_id'), 'cart_items', ['user_id'], unique=False)
    op.drop_column('cart_items', 'buyer_id')
    # ### end Alembic commands ###
