"""Create OrderModelSecond

Revision ID: c57f81b2a8b2
Revises: 34a0c9a1891f
Create Date: 2025-11-27 16:59:16.893529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c57f81b2a8b2'
down_revision: Union[str, Sequence[str], None] = '34a0c9a1891f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
