"""Update ProductModel

Revision ID: febaffba7438
Revises: 992049392221
Create Date: 2025-11-16 21:19:22.691798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'febaffba7438'
down_revision: Union[str, Sequence[str], None] = '992049392221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("\n            setweight(to_tsvector('english', coalesce(name, '')), 'A')\n            ||\n            setweight(to_tsvector('russian', coalesce(name, '')), 'A')\n            ||\n            setweight(to_tsvector('english', coalesce(description, '')), 'B')\n            ||\n            setweight(to_tsvector('russian', coalesce(description, '')), 'B')\n            ", persisted=True), nullable=False))
    op.alter_column('products', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.create_index('ix_products_tsv_gin', 'products', ['tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_tsv_gin', table_name='products', postgresql_using='gin')
    op.alter_column('products', 'price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('products', 'tsv')
    # ### end Alembic commands ###
